name: 'Close Pull Request'
description: 'Close pull request'
inputs:
  token:
    description: "Token to authenticate on behalf of GitHub Actions"
    type: string
    required: true
    default: ''

  comment:
    description: "Comment describes pull request reject reason "
    type: string
    required: false
    default: ''
 
runs:
  using: 'node16'
  main: 'index.js'