name: 'Close Pull Request'
description: 'Close pull request'
inputs:
  github_token:
    description: "Token to authenticate on behalf of GitHub Actions"
    default: ${{ github.token }}

  comment:
    description: "Comment describes pull request reject reason "
    type: string
    required: false
    default: ''
 
runs:
  using: 'node16'
  main: 'index.js'